import UIKit

var ilce: String = "Kadıköy"
var kita: String = "Avrupa"
var faks: String = "02120000000"
var postaKodu: String = "34710"
var instaAdresi: String = "_akbasmert"
var calistiginBolum: String = "IOS"
var urunMiktari: Int = 50
var musteriSoyadi: String = "Akbaş"
var odemeMiktari: Double = 250.75
var dogumTarihi: Date = Date()
var borc: Double = 1000.0
var medeniHal: String = "Bekar"
var videoYorumu: String = "Güzel video"
var odemeSaati: String = "10:30"
var eftMiktari: Double = 500.0
var satilanMiktar: Int = 20
var telefonModeli: String = "iPhone 12"
var dergiAdi: String = "My Home"
var basimTarihi: Date = Date()
var zamMiktari: Double = 670.0
var daireSayisi: Int = 40
var enlem: Double = 98.04
var boylam: Double = 56.9784
var yemekAdi: String = "Pide"
var urunFiyati: Double = 75.50
var sirket: String = "Apple"
var videoAdi: String = "Yemek tarifi"
var muzikSuresi: Double = 2.98
var mekanPuani: Int = 9
var dosyaAdi: String = "dosya1"
var resimFormati: String = "JPEG"
var renk: String = "sarı"
var renkKodu: String = "#FF0000"
var bilgisayarModeli: String = "MacBook Air"
var ekranBoyutu: String = "15 inç"
var kullanimSuresi: Int = 100
var basinc: Double = 1022.90
var etkinlikGunu: Date = Date()
var odemeGunu: Date = Date()
var yolculukCikisTarihi: Date = Date()
var mahalleAdi: String = "Karşıyaka"
var otobusHatti: String = "c55"
var kullanilanDakika: Int = 60
var kargoTakipNo: String = "24234234234"
var kuponSuresi: Int = 30
var kuponKodu: String = "INDIRIM40"
var faturaTarihi: Date = Date()

